-- ARCHIVELOG mode, archive destination and minimal supplemental logging. Runs once as SYS in CDB$ROOT.
-- Tables enable ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS in their own setup.sql.
WHENEVER SQLERROR EXIT FAILURE
ALTER SYSTEM SET db_recovery_file_dest_size = 20G SCOPE=BOTH;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/fra' SCOPE=BOTH;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER PLUGGABLE DATABASE FREEPDB1 SAVE STATE;

ALTER SYSTEM ARCHIVE LOG CURRENT;
