BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl12 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl12 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE SEQUENCE olrt_ddl12.sq;
CREATE TABLE olrt_ddl12.t (id NUMBER(10) DEFAULT olrt_ddl12.sq.NEXTVAL PRIMARY KEY, qty NUMBER(15,3) DEFAULT 0.000 NOT NULL,
  v VARCHAR2(20) DEFAULT 'dflt', d DATE DEFAULT DATE '2026-01-01', ts DATE DEFAULT SYSDATE);
ALTER TABLE olrt_ddl12.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl12.t (v) VALUES ('seed');
COMMIT;
