BEGIN EXECUTE IMMEDIATE 'DROP USER rt_bin CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_bin IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_bin.t_bin (id NUMBER(10) PRIMARY KEY, f BINARY_FLOAT, d BINARY_DOUBLE);
ALTER TABLE rt_bin.t_bin ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
