BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_a2 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_a2 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_a2.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40), q NUMBER(15,3));
ALTER TABLE olrt_a2.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_a2.t VALUES (1, 'initial', 0);
COMMIT;
