BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl6 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl6 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl6.t (id NUMBER(10) CONSTRAINT t_pk PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40));
ALTER TABLE olrt_ddl6.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl6.t SELECT LEVEL, LEVEL, 'r' FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
