BEGIN EXECUTE IMMEDIATE 'DROP USER OLRT_ST1 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER OLRT_ST1 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE OLRT_ST1.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40), q NUMBER(15,3), d DATE);
ALTER TABLE OLRT_ST1.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO OLRT_ST1.t SELECT LEVEL, 'initial-' || LEVEL, LEVEL, DATE '2026-01-01' FROM dual CONNECT BY LEVEL <= 50;
COMMIT;
