BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_dt CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_dt IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_dt.t (id NUMBER(10) PRIMARY KEY, d DATE, t0 TIMESTAMP(0), t3 TIMESTAMP(3), t6 TIMESTAMP(6), t9 TIMESTAMP(9));
ALTER TABLE olrt_dt.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
