BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_c9 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_c9 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
-- only PK supplemental logging: an UPDATE's redo carries the PK and the changed columns
CREATE TABLE olrt_c9.tpk (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3) NOT NULL, txt VARCHAR2(40) NOT NULL,
                          d DATE NOT NULL, opt VARCHAR2(10));
ALTER TABLE olrt_c9.tpk ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
INSERT INTO olrt_c9.tpk SELECT LEVEL, LEVEL + 0.5, 'row ' || LEVEL, DATE '2026-01-01' + LEVEL, 'o' FROM dual CONNECT BY LEVEL <= 5;
-- virtual column, NOT NULL: in JDBC metadata, never in redo
CREATE TABLE olrt_c9.tv (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3) NOT NULL,
                         dbl NUMBER(15,3) GENERATED ALWAYS AS (qty * 2) VIRTUAL NOT NULL,
                         lbl VARCHAR2(20) GENERATED ALWAYS AS (CAST('q' || TO_CHAR(id) AS VARCHAR2(20))) VIRTUAL NOT NULL);
ALTER TABLE olrt_c9.tv ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_c9.tv (id, qty) SELECT LEVEL, LEVEL FROM dual CONNECT BY LEVEL <= 5;
COMMIT;
