BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_nolog CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_nolog IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_nolog.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3)) NOLOGGING;
ALTER TABLE olrt_nolog.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
