BEGIN EXECUTE IMMEDIATE 'DROP USER OLRT_RSL2 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER OLRT_RSL2 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE OLRT_RSL2.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40), q NUMBER(15,3), d DATE);
ALTER TABLE OLRT_RSL2.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
DECLARE s VARCHAR2(32767) := 'CREATE TABLE OLRT_RSL2.w (id NUMBER(10) PRIMARY KEY';
BEGIN
  FOR i IN 2..300 LOOP s := s || ', c' || i || CASE MOD(i, 3) WHEN 0 THEN ' DATE' WHEN 1 THEN ' NUMBER(15,3)' ELSE ' VARCHAR2(20)' END; END LOOP;
  EXECUTE IMMEDIATE s || ')';
END;
/
ALTER TABLE OLRT_RSL2.w ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO OLRT_RSL2.t VALUES (1, 'initial', 0, DATE '2026-01-01');
INSERT INTO OLRT_RSL2.w (id, c2, c255, c256, c299, c300) VALUES (1, 'initial', DATE '2026-01-01', 1, 'x', DATE '2026-01-01');
COMMIT;
