BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_srm CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_srm IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_srm.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), d DATE);
ALTER TABLE olrt_srm.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_srm.t VALUES (1, 1, 'a', DATE '2026-01-01');
INSERT INTO olrt_srm.t VALUES (2, 2, 'b', DATE '2026-01-02');
INSERT INTO olrt_srm.t VALUES (3, 3, 'c', DATE '2026-01-03');
COMMIT;
