BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_nopk CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_nopk IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_nopk.t (item_no VARCHAR2(20), pack_no NUMBER(10), qty NUMBER(15,3), pack_break CHAR(1));
ALTER TABLE olrt_nopk.t ADD SUPPLEMENTAL LOG GROUP t_key (item_no, pack_no) ALWAYS;
ALTER TABLE olrt_nopk.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_nopk.t VALUES ('P1', 1, 10.000, 'N');
INSERT INTO olrt_nopk.t VALUES ('P1', 2, 100.000, 'N');
CREATE TABLE olrt_nopk.u (k NUMBER(10) NOT NULL, v VARCHAR2(10));
CREATE UNIQUE INDEX olrt_nopk.u_k ON olrt_nopk.u (k);
ALTER TABLE olrt_nopk.u ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_nopk.u VALUES (1, 'a');
INSERT INTO olrt_nopk.u VALUES (2, 'b');
COMMIT;
