BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_vc CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_vc IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_vc.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(20), b VARCHAR2(20), c VARCHAR2(20));
ALTER TABLE olrt_vc.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
