BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_n1 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_n1 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_n1.t (id NUMBER(10) PRIMARY KEY, f NUMBER(1,0), g NUMBER(1,0) DEFAULT 0 NOT NULL, q NUMBER(15,3), v VARCHAR2(10));
ALTER TABLE olrt_n1.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_n1.t VALUES (1, 0, 0, 0, '0');
INSERT INTO olrt_n1.t VALUES (2, 1, 1, 1.000, '1');
INSERT INTO olrt_n1.t VALUES (3, NULL, 0, NULL, NULL);
COMMIT;
