BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_pt CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_pt IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_pt.r (id NUMBER(10) PRIMARY KEY, region NUMBER(3), txt VARCHAR2(30), d DATE)
  PARTITION BY RANGE (region) (PARTITION p1 VALUES LESS THAN (10), PARTITION p2 VALUES LESS THAN (20), PARTITION p3 VALUES LESS THAN (MAXVALUE)) ENABLE ROW MOVEMENT;
ALTER TABLE olrt_pt.r ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_pt.r SELECT LEVEL, MOD(LEVEL, 25), 'r' || LEVEL, DATE '2026-01-01' + LEVEL FROM dual CONNECT BY LEVEL <= 50;
CREATE TABLE olrt_pt.i (id NUMBER(10) PRIMARY KEY, d DATE NOT NULL, txt VARCHAR2(30))
  PARTITION BY RANGE (d) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (PARTITION p0 VALUES LESS THAN (DATE '2026-01-01'));
ALTER TABLE olrt_pt.i ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_pt.i SELECT LEVEL, DATE '2025-12-01' + LEVEL * 10, 'i' || LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
