BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_mr CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_mr IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_mr.T (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), d DATE);
ALTER TABLE olrt_mr.T ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_mr.T SELECT LEVEL, LEVEL * 1.5, 'row ' || LEVEL, DATE '2026-01-01' + LEVEL FROM dual CONNECT BY LEVEL <= 20;
COMMIT;
CREATE TABLE olrt_mr.T2 (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), d DATE);
ALTER TABLE olrt_mr.T2 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_mr.T2 SELECT LEVEL, LEVEL * 1.5, 'row ' || LEVEL, DATE '2026-01-01' + LEVEL FROM dual CONNECT BY LEVEL <= 20;
COMMIT;
