BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl14 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl14 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl14.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(20), qty NUMBER(15,3), d DATE);
ALTER TABLE olrt_ddl14.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl14.t SELECT LEVEL, 'a' || LEVEL, LEVEL, DATE '2026-01-01' + LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
