BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_tn CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_tn IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_tn.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(10), b NUMBER(10,2), c DATE, d VARCHAR2(10), e NUMBER(5));
ALTER TABLE olrt_tn.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_tn.t VALUES (1, 'a', 1, DATE '2026-01-01', 'd', 5);
INSERT INTO olrt_tn.t (id, a) VALUES (2, 'a');
INSERT INTO olrt_tn.t (id) VALUES (3);
INSERT INTO olrt_tn.t (id, e) VALUES (4, 4);
COMMIT;
