BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_gap CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_gap IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_gap.t (id NUMBER(10) PRIMARY KEY, txt VARCHAR2(40));
ALTER TABLE olrt_gap.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
COMMIT;
