BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_wb CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_wb IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
BEGIN
  FOR tn IN 1 .. 2 LOOP
    DECLARE s VARCHAR2(32000) := 'CREATE TABLE olrt_wb.t' || CASE WHEN tn = 2 THEN '2' END || ' (id NUMBER(10) PRIMARY KEY';
    BEGIN
      FOR i IN 2 .. 313 LOOP
        s := s || ', c' || i || ' ' || CASE MOD(i, 3) WHEN 0 THEN 'VARCHAR2(40)' WHEN 1 THEN 'NUMBER(15,3)' ELSE 'DATE' END;
      END LOOP;
      EXECUTE IMMEDIATE s || ')';
      EXECUTE IMMEDIATE 'ALTER TABLE olrt_wb.t' || CASE WHEN tn = 2 THEN '2' END || ' ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS';
    END;
  END LOOP;
END;
/
-- fill 300 rows in t with every column set
DECLARE s VARCHAR2(32000) := 'INSERT INTO olrt_wb.t SELECT LEVEL';
BEGIN
  FOR i IN 2 .. 313 LOOP
    s := s || ', ' || CASE MOD(i, 3) WHEN 0 THEN '''v'' || LEVEL || ''_' || i || '''' WHEN 1 THEN 'LEVEL * 1.5 + ' || i ELSE 'DATE ''2026-01-01'' + LEVEL' END;
  END LOOP;
  EXECUTE IMMEDIATE s || ' FROM dual CONNECT BY LEVEL <= 300';
END;
/
COMMIT;
