BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl11 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl11 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl11.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(20), qty NUMBER(15,3));
ALTER TABLE olrt_ddl11.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl11.t SELECT LEVEL, 'a' || LEVEL, LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
