BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_cmp CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_cmp IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_cmp.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40)) COMPRESS BASIC;
ALTER TABLE olrt_cmp.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
