BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ch CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ch IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ch.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(400), b VARCHAR2(400), c VARCHAR2(400), n NUMBER(10)) PCTFREE 0;
ALTER TABLE olrt_ch.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ch.t SELECT LEVEL, NULL, NULL, NULL, LEVEL FROM dual CONNECT BY LEVEL <= 2000;
COMMIT;
