BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_oc CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_oc IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_oc.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(40), n NUMBER(10,2), d DATE) ROW STORE COMPRESS ADVANCED;
ALTER TABLE olrt_oc.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_oc.t SELECT LEVEL, 'same text', 1.5, DATE '2026-01-01' FROM dual CONNECT BY LEVEL <= 500;
COMMIT;
