BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_bin CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_bin IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_bin.t (id NUMBER(10) PRIMARY KEY, f BINARY_FLOAT, d BINARY_DOUBLE);
ALTER TABLE olrt_bin.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
