BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_tsi CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_tsi IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_tsi.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3));
ALTER TABLE olrt_tsi.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_tsi.t VALUES (1, 0);
COMMIT;
