BEGIN EXECUTE IMMEDIATE 'DROP USER rt_xid CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_xid IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_xid.t (id NUMBER(10) PRIMARY KEY, tx VARCHAR2(16));
ALTER TABLE rt_xid.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
COMMIT;
