BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_srb CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_srb IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_srb.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(5) CHECK (qty < 1000), txt VARCHAR2(10));
ALTER TABLE olrt_srb.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_srb.t SELECT LEVEL, LEVEL, 'r' || LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
