BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_txt CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_txt IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_txt.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(200), nv NVARCHAR2(50));
ALTER TABLE olrt_txt.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
