BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_cv CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_cv IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_cv.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), small NUMBER(5,2), intnum NUMBER(38),
                        anynum NUMBER, flt FLOAT, f BINARY_FLOAT, d BINARY_DOUBLE);
ALTER TABLE olrt_cv.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
