BEGIN EXECUTE IMMEDIATE 'DROP USER rt_ot CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_ot IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_ot.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40));
ALTER TABLE rt_ot.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO rt_ot.t VALUES (1, 'existing');
COMMIT;
