BEGIN EXECUTE IMMEDIATE 'DROP USER rt_num CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_num IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_num.t_num (
    id      NUMBER(10) PRIMARY KEY,
    qty     NUMBER(15,3),
    qty2    NUMBER(15,3),
    anynum  NUMBER,
    intnum  NUMBER(38),
    small   NUMBER(5,2),
    flt     FLOAT
);
ALTER TABLE rt_num.t_num ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO rt_num.t_num VALUES (100, 1.000, 2.500, 1, 1, 1.00, 1);
INSERT INTO rt_num.t_num VALUES (101, 5.250, 0.000, 7, 7, 0.50, 2.5);
COMMIT;
