BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl6 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl6 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl6.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(20), b NUMBER(15,3), c DATE, d VARCHAR2(20), e NUMBER(5));
ALTER TABLE olrt_ddl6.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl6.t SELECT LEVEL, 'a' || LEVEL, LEVEL / 4, DATE '2026-01-01' + LEVEL, 'd' || LEVEL, LEVEL FROM dual CONNECT BY LEVEL <= 20;
COMMIT;
