BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl5 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl5 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl5.t (id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, qty NUMBER(15,3),
                          dflt VARCHAR2(10) DEFAULT ON NULL 'dflt', gone VARCHAR2(10));
ALTER TABLE olrt_ddl5.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl5.t (qty) VALUES (0);
COMMIT;
