BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_term CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_term IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_term.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(20));
ALTER TABLE olrt_term.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_term.t VALUES (1, 'one');
COMMIT;
