BEGIN EXECUTE IMMEDIATE 'DROP USER rt_il CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_il IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_il.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), d DATE);
ALTER TABLE rt_il.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO rt_il.t SELECT LEVEL, LEVEL * 1.5, 'row ' || LEVEL, DATE '2026-01-01' + LEVEL FROM dual CONNECT BY LEVEL <= 20;
COMMIT;
