BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl9 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl9 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl9.t (id NUMBER(10) PRIMARY KEY, a VARCHAR2(20));
ALTER TABLE olrt_ddl9.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl9.t SELECT LEVEL, 'a' || LEVEL FROM dual CONNECT BY LEVEL <= 30;
COMMIT;
BEGIN
  DECLARE s VARCHAR2(32000) := 'CREATE TABLE olrt_ddl9.w (id NUMBER(10) PRIMARY KEY';
  BEGIN
    FOR i IN 2 .. 312 LOOP
      s := s || ', c' || i || ' ' || CASE MOD(i, 3) WHEN 0 THEN 'VARCHAR2(40)' WHEN 1 THEN 'NUMBER(15,3)' ELSE 'DATE' END;
    END LOOP;
    EXECUTE IMMEDIATE s || ')';
  END;
END;
/
ALTER TABLE olrt_ddl9.w ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl9.w (id, c2, c3, c312) SELECT LEVEL, DATE '2026-01-01', 'w' || LEVEL, 'x' || LEVEL FROM dual CONNECT BY LEVEL <= 30;
COMMIT;
