BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ddl7 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ddl7 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ddl7.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(5), n NUMBER(5,1), n2 NUMBER(8,2));
ALTER TABLE olrt_ddl7.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ddl7.t VALUES (1, 'short', 1234.5, 123456.78);
INSERT INTO olrt_ddl7.t VALUES (2, 'abc', 0.1, 0.01);
COMMIT;
