BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_negsc CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_negsc IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_negsc.t (id NUMBER(10) PRIMARY KEY, h NUMBER(10,-2), z NUMBER(1));
ALTER TABLE olrt_negsc.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
