BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_dp CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_dp IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_dp.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40));
ALTER TABLE olrt_dp.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
