BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_vl CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_vl IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_vl.t (id NUMBER(10) PRIMARY KEY, s VARCHAR2(100), big VARCHAR2(4000), u VARCHAR2(4000 CHAR));
ALTER TABLE olrt_vl.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_vl.t (id, s) VALUES (1, 'start');
COMMIT;
