INSERT INTO olrt_vl.t (id, s) VALUES (10, 'it''s');
INSERT INTO olrt_vl.t (id, s) VALUES (11, 'a|b|c');
INSERT INTO olrt_vl.t (id, s) VALUES (12, 'x;y;z');
INSERT INTO olrt_vl.t (id, s) VALUES (13, 'back\slash \n literal');
INSERT INTO olrt_vl.t (id, s) VALUES (14, 'line1' || CHR(10) || 'line2' || CHR(13) || CHR(9) || 'tab');
INSERT INTO olrt_vl.t (id, s) VALUES (15, 'trailing   ');
INSERT INTO olrt_vl.t (id, s) VALUES (16, '   leading');
INSERT INTO olrt_vl.t (id, s) VALUES (17, '0xDEADBEEF');
INSERT INTO olrt_vl.t (id, s) VALUES (18, '"quoted" and {json: [1,2]}');
INSERT INTO olrt_vl.t (id, s) VALUES (19, 'ÅÄÖåäö é ü ß');
INSERT INTO olrt_vl.t (id, big) VALUES (20, RPAD('x', 4000, 'x'));
INSERT INTO olrt_vl.t (id, big) VALUES (21, RPAD('ab', 3999, 'ab'));
INSERT INTO olrt_vl.t (id, u) VALUES (22, RPAD('Å', 1300, 'Å'));
INSERT INTO olrt_vl.t (id, big, u) VALUES (23, RPAD('q', 4000, 'q'), RPAD('é', 2000, 'é'));
UPDATE olrt_vl.t SET big = RPAD('y', 4000, 'y') WHERE id = 20;
UPDATE olrt_vl.t SET big = 'short' WHERE id = 21;
UPDATE olrt_vl.t SET s = s || '''' || '|' || ';' WHERE id BETWEEN 10 AND 19;
COMMIT;
UPDATE olrt_vl.t SET s = 'a''b' || CHR(10) || 'c\|;' , big = NULL, u = '' WHERE id = 23;
COMMIT;
