BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_sfurd CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_sfurd IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_sfurd.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), changed DATE) ROWDEPENDENCIES;
ALTER TABLE olrt_sfurd.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_sfurd.t (id, qty, txt) SELECT LEVEL, LEVEL, 'r' || LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
