BEGIN EXECUTE IMMEDIATE 'DROP USER rt_tz CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_tz IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_tz.t (id NUMBER(10) PRIMARY KEY, utc_time TIMESTAMP(6));
ALTER TABLE rt_tz.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
COMMIT;
