BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_sfu CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_sfu IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_sfu.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), changed DATE);
ALTER TABLE olrt_sfu.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_sfu.t (id, qty, txt) SELECT LEVEL, LEVEL, 'r' || LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
