BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_ot CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_ot IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_ot.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40));
ALTER TABLE olrt_ot.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_ot.t VALUES (1, 'existing');
COMMIT;
