BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_chr CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_chr IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_chr.t (id NUMBER(10) PRIMARY KEY, flag CHAR(1), c10 CHAR(10), nc NCHAR(5), blank CHAR(3));
ALTER TABLE olrt_chr.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
