BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_lkr CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_lkr IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_lkr.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), changed DATE) ROWDEPENDENCIES;
ALTER TABLE olrt_lkr.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
CREATE OR REPLACE TRIGGER olrt_lkr.t_bu BEFORE INSERT OR UPDATE ON olrt_lkr.t FOR EACH ROW
BEGIN
  :new.txt := 'trg ' || :new.id;
  :new.changed := DATE '2026-10-02';
END;
/
INSERT INTO olrt_lkr.t (id, qty) SELECT LEVEL, LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
