BEGIN EXECUTE IMMEDIATE 'DROP USER rt_numx CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_numx IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_numx.t_numx (id NUMBER(10) PRIMARY KEY, anynum NUMBER);
ALTER TABLE rt_numx.t_numx ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO rt_numx.t_numx VALUES (100, 1);
COMMIT;
