BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_vc CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_vc IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_vc.t (id NUMBER(10) PRIMARY KEY, a NUMBER(10,2), b NUMBER(10,2), total NUMBER GENERATED ALWAYS AS (a + b) VIRTUAL,
  tag VARCHAR2(20) INVISIBLE, txt VARCHAR2(20));
ALTER TABLE olrt_vc.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_vc.t (id, a, b, tag, txt) SELECT LEVEL, LEVEL, LEVEL / 2, 'tag' || LEVEL, 't' || LEVEL FROM dual CONNECT BY LEVEL <= 20;
COMMIT;
