#!/usr/bin/env python3
"""Generates the wide-table fixture and the wide/ scenarios (ERROR 50073 family).

Two table shapes: WIDE.WIDE_278 (278 columns, 30 extended-statistics virtual columns created
before the last 14 columns, MOVE so dataobj != obj) and WIDE.WIDE_313 (313 columns, 4-column key).
All names and values are synthetic.

Output (regenerate with `python3 fixtures/wide/gen.py`, commit the result):
  fixtures/wide/setup.sql            schema WIDE: WIDE_278, WIDE_278_NM, WIDE_278_CH, WIDE_313 + data
  fixtures/wide/verify.sql           structure evidence (run by hand)
  scenarios/wide/<name>/             one scenario per variant
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SCEN = ROOT / "scenarios" / "wide"

A_COLS_FIRST = 264      # created with the table
A_COLS_TOTAL = 278      # C265..C278 added after the extended stats
A_EXT_STATS = 30
B_COLS = 313
B_LAST_NONNULL = 225   # trailing-NULL rows: NULL from col 226 (segment 257+ all NULL)
ROWS = 300


def a_name(i):
    return "ID" if i == 1 else f"C{i}"


def b_name(i):
    return {1: "ID", 2: "POS", 3: "SUBPOS", 4: "SEQ"}.get(i, f"C{i}")


def col_type(i, key_cols):
    if i <= key_cols:
        return "NUMBER(10) NOT NULL"
    if i == 2:                      # WIDE_278 status column
        return "VARCHAR2(2)"
    return {0: "DATE", 1: "NUMBER(15,3)", 2: "VARCHAR2(40)"}[i % 3]


def col_value(i, key_cols, row="l", short=False):
    """SQL expression for column i of row number <row> (CONNECT BY LEVEL)."""
    if i == 1:
        return row
    if i <= key_cols:          # WIDE_313: POS=10, SUBPOS=0, SEQ=1
        return {2: "10", 3: "0", 4: "1"}[i]
    if i == 2:
        return "'OK'"
    t = i % 3
    if t == 0:
        return f"DATE '2026-01-01' + MOD({row}*{i}, 300)"
    if t == 1:
        return f"{row}*1000 + {i} + 0.125"
    if short:
        return f"'s{i}'"
    return f"'R' || {row} || '_C{i}_' || RPAD('x', 12, 'x')"


def create_table(owner, tab, names, ncols, key_cols, pk, pctfree=None):
    cols = ",\n    ".join(f"{names(i)} {col_type(i, key_cols)}" for i in range(1, ncols + 1))
    pf = f" PCTFREE {pctfree}" if pctfree is not None else ""
    return (f"CREATE TABLE {owner}.{tab} (\n    {cols},\n"
            f"    CONSTRAINT {tab}_PK PRIMARY KEY ({pk})\n){pf};\n")


def insert_rows(owner, tab, names, ncols, key_cols, short=False, row="l"):
    cl = ", ".join(names(i) for i in range(1, ncols + 1))
    vals = ",\n       ".join(col_value(i, key_cols, row=row, short=short) for i in range(1, ncols + 1))
    return (f"INSERT INTO {owner}.{tab} ({cl})\nSELECT {vals}\n"
            f"  FROM (SELECT LEVEL l FROM dual CONNECT BY LEVEL <= {ROWS});\nCOMMIT;\n")


def wide_278(tab, move, chained):
    out = [f"\n-- ===== {tab}: 264 cols, 30 ext stats, +14 cols"
           f"{', MOVE' if move else ', no MOVE'}{', PCTFREE 0 + grown rows (migrated/chained)' if chained else ''} =====\n"]
    out.append(create_table("WIDE", tab, a_name, A_COLS_FIRST, 1, "ID", 0 if chained else None))
    out.append("BEGIN\n")
    for k in range(A_EXT_STATS):
        a, b = 2 + 2 * k, 3 + 2 * k
        out.append(f"  DBMS_OUTPUT.PUT_LINE(DBMS_STATS.CREATE_EXTENDED_STATS('WIDE', '{tab}', '(C{a},C{b})'));\n")
    out.append("END;\n/\n")
    for i in range(A_COLS_FIRST + 1, A_COLS_TOTAL + 1):
        out.append(f"ALTER TABLE WIDE.{tab} ADD ({a_name(i)} {col_type(i, 1)});\n")
    out.append(insert_rows("WIDE", tab, a_name, A_COLS_TOTAL, 1, short=chained))
    if move:
        out.append(f"ALTER TABLE WIDE.{tab} MOVE UPDATE INDEXES;\n")
    if chained:
        # rows were packed with short strings at PCTFREE 0 (and repacked by MOVE);
        # growing every VARCHAR2 now forces row migration/chaining
        sets = ", ".join(f"C{i} = 'R' || ID || '_C{i}_' || RPAD('y', 24, 'y')"
                         for i in range(3, A_COLS_TOTAL + 1) if i % 3 == 2)
        out.append(f"UPDATE WIDE.{tab} SET {sets};\nCOMMIT;\n")
    out.append(f"ALTER TABLE WIDE.{tab} ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;\n")
    return "".join(out)


def setup_sql():
    s = ["-- Generated by fixtures/wide/gen.py. Runs in FREEPDB1 as SYS, once per recording run.\n",
         "-- rerunnable: recreate the lab-only WIDE schema from scratch\n"
         "BEGIN EXECUTE IMMEDIATE 'DROP USER wide CASCADE';\n"
         "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;\n/\n"
         "CREATE USER wide IDENTIFIED BY wide DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;\n",
         "GRANT CREATE SESSION, CREATE TABLE TO wide;\n"]
    # WIDE_278: ext stats before the last 14 cols, MOVE after load
    s.append(wide_278("WIDE_278", move=True, chained=False))
    s.append(wide_278("WIDE_278_NM", move=False, chained=False))
    # chained variant: build, MOVE (dataobj != obj), then grow rows
    s.append(wide_278("WIDE_278_CH", move=True, chained=True))
    s.append("\n-- ===== WIDE_313: 313 cols, no ext stats =====\n")
    s.append(create_table("WIDE", "WIDE_313", b_name, B_COLS, 4, "ID, POS, SUBPOS, SEQ"))
    s.append(insert_rows("WIDE", "WIDE_313", b_name, B_COLS, 4))
    # trailing-NULL rows: ID 1001..1300, last non-null column C225, C226..C313 NULL
    s.append(insert_rows("WIDE", "WIDE_313", b_name, B_LAST_NONNULL, 4, row="(1000 + l)"))
    s.append("ALTER TABLE WIDE.WIDE_313 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;\n")
    s.append("ANALYZE TABLE WIDE.WIDE_278 COMPUTE STATISTICS;\n"
             "ANALYZE TABLE WIDE.WIDE_278_NM COMPUTE STATISTICS;\n"
             "ANALYZE TABLE WIDE.WIDE_278_CH COMPUTE STATISTICS;\n"
             "ANALYZE TABLE WIDE.WIDE_313 COMPUTE STATISTICS;\n")
    return "".join(s)


VERIFY = """-- Generated by fixtures/wide/gen.py. Structure evidence, run by hand in FREEPDB1.
SET PAGESIZE 500 LINESIZE 200
COLUMN owner FORMAT A6
COLUMN table_name FORMAT A10
COLUMN column_name FORMAT A32
COLUMN data_type FORMAT A10
COLUMN object_name FORMAT A10

PROMPT == object_id vs data_object_id
SELECT object_name, object_id, data_object_id,
       CASE WHEN object_id != data_object_id THEN 'dataobj!=obj' ELSE 'same' END d
  FROM dba_objects WHERE owner = 'WIDE' AND object_type = 'TABLE' ORDER BY object_name;

PROMPT == column counts (real / hidden virtual / max segment / max internal)
SELECT table_name,
       COUNT(CASE WHEN hidden_column = 'NO' THEN 1 END) real_cols,
       COUNT(CASE WHEN hidden_column = 'YES' AND virtual_column = 'YES' THEN 1 END) hidden_virtual,
       MAX(segment_column_id) max_seg, MAX(internal_column_id) max_int
  FROM dba_tab_cols WHERE owner = 'WIDE' GROUP BY table_name ORDER BY table_name;

PROMPT == WIDE_278: hidden SYS_STS columns + the shifted columns (C264..C278)
SELECT column_name, data_type, hidden_column hid, virtual_column virt,
       column_id, segment_column_id seg, internal_column_id int_id
  FROM dba_tab_cols
 WHERE owner = 'WIDE' AND table_name = 'WIDE_278'
   AND (column_name LIKE 'SYS\\_STS%' ESCAPE '\\' OR internal_column_id >= 264)
 ORDER BY internal_column_id;

PROMPT == WIDE_313: full row (ID 11) vs trailing-NULL row (ID 1011)
COLUMN c225 FORMAT A30
COLUMN c226 FORMAT A30
SELECT id, c225, c226, c313 FROM wide.wide_313 WHERE id IN (11, 1011) ORDER BY id;

PROMPT == chained/migrated rows (ANALYZE chain_cnt)
SELECT table_name, num_rows, chain_cnt, avg_row_len, pct_free
  FROM dba_tables WHERE owner = 'WIDE' ORDER BY table_name;

PROMPT == supplemental logging: database (CDB view) and table log groups
SELECT supplemental_log_data_min min, supplemental_log_data_pk pk, supplemental_log_data_ui ui,
       supplemental_log_data_fk fk, supplemental_log_data_all "ALL" FROM v$database;
SELECT table_name, log_group_type, always FROM dba_log_groups WHERE owner = 'WIDE' ORDER BY table_name;
"""

# ---- variants ---------------------------------------------------------------
# Every variant uses its own rows: base = 10*n. A rows base+1..3, B row ID=base+1.
NOOP_LOW = [10, 11, 12, 13, 14]
NOOP_HIGH = [200, 201, 202, 203, 204]
NOOP_SHIFT = [265, 266, 267, 268, 269, 270]
NOOP_ALL = list(range(2, A_COLS_TOTAL + 1))
B_HIGH = [300, 301, 302]


def noop(tab, cols, rid):
    sets = ", ".join(f"C{c} = C{c}" for c in cols)
    return f"UPDATE WIDE.{tab} SET {sets} WHERE ID = {rid};\n"


def upd_date(tab, dcol, rid, status=False):
    st = "C2 = 'XX', " if status else ""
    return f"UPDATE WIDE.{tab} SET {st}C{dcol} = DATE '2026-10-02' WHERE ID = {rid};\n"


def b_op(op, rid):
    # all B ops hit the trailing-NULL row (ID+1000) except "delete-full"
    if op == "delete-full":
        return f"DELETE FROM WIDE.WIDE_313 WHERE ID = {rid} AND POS = 10 AND SUBPOS = 0 AND SEQ = 1;\n"
    rid += 1000
    if op == "delete":
        return f"DELETE FROM WIDE.WIDE_313 WHERE ID = {rid} AND POS = 10 AND SUBPOS = 0 AND SEQ = 1;\n"
    if op == "update-low":
        return f"UPDATE WIDE.WIDE_313 SET C7 = C7 + 1 WHERE ID = {rid};\n"
    if op == "update-high":
        sets = ", ".join(f"C{c} = C{c}" for c in B_HIGH)
        return f"UPDATE WIDE.WIDE_313 SET {sets} WHERE ID = {rid};\n"
    if op == "update-all":
        sets = ", ".join(f"C{c} = C{c}" for c in range(5, B_COLS + 1))
        return f"UPDATE WIDE.WIDE_313 SET {sets} WHERE ID = {rid};\n"
    raise ValueError(op)


VARIANTS = [
    # name, A table, date col for #1/#4, no-op cols for #2, B op, order, description
    ("v01-repro",          "WIDE_278",    3,   NOOP_LOW,   "delete", "repro", "repro order, date C3, noop low, delete B"),
    ("v02-noop-shift",    "WIDE_278",    3,   NOOP_SHIFT, "delete", "repro", "noop on shifted cols C265-C270"),
    ("v03-date-high",     "WIDE_278",    201, NOOP_LOW,   "delete", "repro", "date C201 (high piece), noop low"),
    ("v04-date-shift",    "WIDE_278",    270, NOOP_SHIFT, "delete", "repro", "date C270 + noop shifted"),
    ("v05-noop-high",     "WIDE_278",    3,   NOOP_HIGH,  "delete", "repro", "noop on C200-C204"),
    ("v06-noop-all",      "WIDE_278",    3,   NOOP_ALL,   "delete", "repro", "noop on all 277 non-key cols"),
    ("v07-b-upd-low",     "WIDE_278",    3,   NOOP_SHIFT, "update-low", "repro", "B update C7 instead of delete"),
    ("v08-b-upd-high",    "WIDE_278",    3,   NOOP_SHIFT, "update-high", "repro", "B noop update C300-C302"),
    ("v09-b-upd-all",     "WIDE_278",    3,   NOOP_SHIFT, "update-all", "repro", "B noop update all 309 cols"),
    ("v10-nomove",        "WIDE_278_NM", 3,   NOOP_LOW,   "delete", "repro", "A without MOVE (dataobj=obj)"),
    ("v11-nomove-shift",  "WIDE_278_NM", 270, NOOP_SHIFT, "delete", "repro", "A without MOVE, shifted cols"),
    ("v12-chained",       "WIDE_278_CH", 3,   NOOP_LOW,   "delete", "repro", "A migrated/chained rows, PCTFREE 0"),
    ("v13-chained-shift", "WIDE_278_CH", 270, NOOP_SHIFT, "delete", "repro", "A chained, shifted cols"),
    ("v14-b-first",       "WIDE_278",    3,   NOOP_SHIFT, "delete", "b-first", "delete B first, then A x3"),
    ("v15-no-b",          "WIDE_278",    3,   NOOP_SHIFT, "delete", "no-b", "control: A x3 only, no B"),
    ("v16-del-then-upd",  "WIDE_278",    3,   NOOP_SHIFT, "delete", "del-upd", "minimal: delete B, update A (date+status)"),
    ("v17-repro-fullrow",  "WIDE_278",    3,   NOOP_LOW,   "delete-full", "repro", "control: as v01 but deleted B row fully populated"),
    ("v19-split-txn",     "WIDE_278",    3,   NOOP_LOW,   "delete", "split", "delete B + COMMIT, then A update in a 2nd txn"),
    ("v18-shift-fullrow", "WIDE_278",    270, NOOP_SHIFT, "delete-full", "repro", "control: as v04 but deleted B row fully populated"),
]


GUARDS = "ERROR 50073 after DELETE on a >256-column table (fixed in v2.0.0-ahlsell.1, " \
         "branch fix/50073-delete-valuesmax)"
EXTRA = {
    "v01-repro": "The shape that triggers ERROR 50073: DELETE of a WIDE_313 row whose columns from "
                "segment 257 on are NULL, then an UPDATE on WIDE_278 touching a column above 256. "
                "Must FAIL on 2.0.0 and PASS on v2.0.0-ahlsell.1.",
    "v16-del-then-upd": "Minimal 50073 trigger: one DELETE on WIDE_313 (trailing NULLs), one UPDATE on WIDE_278.",
    "v15-no-b": "Control: no WIDE_313 delete, so 50073 must not fire on any image.",
    "v17-repro-fullrow": "Control: the deleted WIDE_313 row is fully populated (no trailing NULLs).",
    "v18-shift-fullrow": "Control: as v04 with a fully populated WIDE_313 row.",
    "v19-split-txn": "DELETE and UPDATE in two transactions: the stale builder state crosses a commit.",
    "v12-chained": "WIDE_278_CH has PCTFREE 0 and grown rows, so updates hit migrated/chained rows.",
    "v13-chained-shift": "Chained rows plus the columns shifted by the extended-stats virtual columns.",
    "v10-nomove": "WIDE_278_NM was never MOVEd, so dataobj = obj (the other variants have dataobj != obj).",
}


def variant_sql(n, v):
    name, tab, dcol, ncols, bop, order, desc = v
    base = 10 * n
    r1, r2, r3, rb = base + 1, base + 2, base + 3, base + 1
    s1 = upd_date(tab, dcol, r1)
    s2 = noop(tab, ncols, r2)
    s3 = b_op(bop, rb)
    s4 = upd_date(tab, dcol, r3, status=True)
    body = {"repro": [s1, s2, s3, s4], "b-first": [s3, s1, s2, s4],
            "no-b": [s1, s2, s4], "del-upd": [s3, s4], "split": [s3, "COMMIT;\n", s4]}[order]
    return f"-- {name}: {desc}\n" + "".join(body) + "COMMIT;\n"


def write_scenario(name, tables, desc, workload, readme, tags, known=None):
    d = SCEN / name
    d.mkdir(parents=True, exist_ok=True)
    toml = [f'description = "{desc}"',
            f"tags = {tags!r}".replace("'", '"'),
            'fixtures = ["wide"]',
            "tables = [" + ", ".join(f'"WIDE.{t}"' for t in tables) + "]",
            f'guards = "{GUARDS}"' if "50073" in tags else 'guards = ""']
    if known:
        toml.append("\n[known_issue]")
        toml += [f'{k} = "{v}"' for k, v in known.items()]
    (d / "scenario.toml").write_text("\n".join(toml) + "\n")
    (d / "workload.sql").write_text(workload)
    (d / "README.md").write_text(readme.strip() + "\n")


def main():
    (HERE / "setup.sql").write_text(setup_sql())
    (HERE / "verify.sql").write_text(VERIFY)
    for n, v in enumerate(VARIANTS, start=1):
        name, tab, desc = v[0], v[1], v[6]
        readme = (f"{desc}. {EXTRA.get(name, '')}\n\nWide-table variant "
                  f"(filter on {tab} and WIDE_313 together; the bug needs both tables in the filter). "
                  f"Guards {GUARDS}.")
        write_scenario(name, [tab, "WIDE_313"], desc, variant_sql(n, v), readme, ["wide", "50073"])
    print(f"wrote fixture + {len(VARIANTS)} scenarios")


if __name__ == "__main__":
    main()
