-- Generated by fixtures/wide/gen.py. Structure evidence, run by hand in FREEPDB1.
SET PAGESIZE 500 LINESIZE 200
COLUMN owner FORMAT A6
COLUMN table_name FORMAT A10
COLUMN column_name FORMAT A32
COLUMN data_type FORMAT A10
COLUMN object_name FORMAT A10

PROMPT == object_id vs data_object_id
SELECT object_name, object_id, data_object_id,
       CASE WHEN object_id != data_object_id THEN 'dataobj!=obj' ELSE 'same' END d
  FROM dba_objects WHERE owner = 'WIDE' AND object_type = 'TABLE' ORDER BY object_name;

PROMPT == column counts (real / hidden virtual / max segment / max internal)
SELECT table_name,
       COUNT(CASE WHEN hidden_column = 'NO' THEN 1 END) real_cols,
       COUNT(CASE WHEN hidden_column = 'YES' AND virtual_column = 'YES' THEN 1 END) hidden_virtual,
       MAX(segment_column_id) max_seg, MAX(internal_column_id) max_int
  FROM dba_tab_cols WHERE owner = 'WIDE' GROUP BY table_name ORDER BY table_name;

PROMPT == WIDE_278: hidden SYS_STS columns + the shifted columns (C264..C278)
SELECT column_name, data_type, hidden_column hid, virtual_column virt,
       column_id, segment_column_id seg, internal_column_id int_id
  FROM dba_tab_cols
 WHERE owner = 'WIDE' AND table_name = 'WIDE_278'
   AND (column_name LIKE 'SYS\_STS%' ESCAPE '\' OR internal_column_id >= 264)
 ORDER BY internal_column_id;

PROMPT == WIDE_313: full row (ID 11) vs trailing-NULL row (ID 1011)
COLUMN c225 FORMAT A30
COLUMN c226 FORMAT A30
SELECT id, c225, c226, c313 FROM wide.wide_313 WHERE id IN (11, 1011) ORDER BY id;

PROMPT == chained/migrated rows (ANALYZE chain_cnt)
SELECT table_name, num_rows, chain_cnt, avg_row_len, pct_free
  FROM dba_tables WHERE owner = 'WIDE' ORDER BY table_name;

PROMPT == supplemental logging: database (CDB view) and table log groups
SELECT supplemental_log_data_min min, supplemental_log_data_pk pk, supplemental_log_data_ui ui,
       supplemental_log_data_fk fk, supplemental_log_data_all "ALL" FROM v$database;
SELECT table_name, log_group_type, always FROM dba_log_groups WHERE owner = 'WIDE' ORDER BY table_name;
