BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_rtrg CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_rtrg IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_rtrg.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3), txt VARCHAR2(40), changed DATE);
ALTER TABLE olrt_rtrg.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_rtrg.t (id, qty, txt) SELECT LEVEL, LEVEL, 'r' || LEVEL FROM dual CONNECT BY LEVEL <= 10;
COMMIT;
CREATE OR REPLACE TRIGGER olrt_rtrg.t_bu BEFORE INSERT OR UPDATE ON olrt_rtrg.t FOR EACH ROW
BEGIN
  :new.txt := 'trg ' || :new.id;
  :new.changed := DATE '2026-10-02';
END;
/
