BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_c14 CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_c14 IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_c14.t (id NUMBER(10) PRIMARY KEY, qty NUMBER(15,3) NOT NULL, txt VARCHAR2(40));
ALTER TABLE olrt_c14.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_c14.t SELECT LEVEL, LEVEL, 'row ' || LEVEL FROM dual CONNECT BY LEVEL <= 5;
COMMIT;
