BEGIN EXECUTE IMMEDIATE 'DROP USER rt_gap CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER rt_gap IDENTIFIED BY test QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE rt_gap.t (id NUMBER(10) PRIMARY KEY, v VARCHAR2(40));
ALTER TABLE rt_gap.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
COMMIT;
