BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_aut CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_aut IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_aut.t (id NUMBER(10) PRIMARY KEY, txt VARCHAR2(40));
ALTER TABLE olrt_aut.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
CREATE OR REPLACE PROCEDURE olrt_aut.autolog(p_id NUMBER, p_txt VARCHAR2) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO olrt_aut.t VALUES (p_id, p_txt);
  COMMIT;
END;
/
