BEGIN EXECUTE IMMEDIATE 'DROP USER olrt_tiny CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
CREATE USER olrt_tiny IDENTIFIED BY olrt QUOTA UNLIMITED ON users DEFAULT TABLESPACE users;
CREATE TABLE olrt_tiny.t (id NUMBER(10) PRIMARY KEY, a NUMBER, b NUMBER);
ALTER TABLE olrt_tiny.t ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO olrt_tiny.t VALUES (1000, 1, 1);
COMMIT;
